# Project information
site_name: Portfolio Social Robot Design
site_url: https://hilkeb.github.io/social-robot-design-portfolio
site_author: HilkeB
site_description: 

# Copyright
copyright: 

# Theme
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.tooltips
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - toc.follow
    - navigation.footer
  icon:
    logo: logo
  palette:
    primary: purple
    accent: indigo

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Project:
    - Week 1: project1.md
    - Week 2: project2.md
    - Week 3: project3.md
    - Week 4: project4.md
    - Week 5: project5.md
    - Week 6: project6.md
    - Week 7: project7.md
    - Week 8: project8.md
  - Reflection: 
    - Week 1: reflection1.md
    - Week 2: reflection2.md
    - Week 3: reflection3.md
    - Week 4: reflection4.md
    - Week 5: reflection5.md
    - Week 6: reflection6.md
    - Week 7: reflection7.md
    - Week 8: reflection8.md
