# Project information
site_name: Material for MkDocs
site_url: 
site_author: 
site_description: 

# Repository
repo_name: 
repo_url: 

# Copyright
copyright: 

# Theme
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.tooltips
    - navigation.sections
  icon:
    logo: logo

# Plugins
plugins:
  - projects:
      projects_dir: examples
      projects_config_transform: !!python/name:examples.transform
      log_level: info

# Hooks
hooks:
  - hooks/archive.py

validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    absolute_links: warn
    unrecognized_links: warn


# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true