# Project information
site_name: Material for MkDocs
site_url: 
site_author: 
site_description: 

# Repository
repo_name: 
repo_url: 

# Copyright
copyright: 

# Theme
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.tooltips
    - navigation.sections
  icon:
    logo: logo

# Extensions
markdown_extensions: