# Project information
site_name: Material for MkDocs
site_url: 
site_author: 
site_description: 

# Repository
repo_name: 
repo_url: 

# Copyright
copyright: 

# Theme
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.tooltips
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - toc.follow
  icon:
    logo: logo
  palette:
    primary: purple
    accent: indigo

# Extensions
markdown_extensions:

nav:
  - Home: index.md
  - Week 1: 
    - Project: week1/project.md
    - Reflection: week1/reflection.md