# Project information
site_name: Portfolio Social Robot Design
site_url: https://hilkeb.github.io/social-robot-design-portfolio
site_author: HilkeB
site_description: 

# Copyright
copyright: 

# Theme
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.tooltips
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - toc.follow
  icon:
    logo: logo
  palette:
    primary: purple
    accent: indigo

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Project:
    - Week 1: week1/project.md
  - Reflection: 
    - Reflection: week1/reflection.md
